### ISSUE TITLE
All project files scanned instead of the configured folders

### ISSUE THREAD

**Issue by equilerex** [syllant/idea-plugin-remotesynchronizer#14]
Hi there,

i've installed the plugin, configured it to watch a small folder with 20 css files... 
it works as intended however, every time the sync detects a save and runs, it freezes intellij for a minute...   often it even ends up in an endless freeze loop until i kill it with ctrl+alt+del

from the log i can see that it is probably since it is scanning the whole project for changes once the sync starts to run... i can see all the project files listed in the log and get the result as:
1 file copied
42365 files ignored

if i disable the log entries for "source paths", "exluded paths" and "identical" files, the freeze is a bit shorter for about 20 seconds but and i get "1 file copied, 20 ignored" but seeing how long it freezes it, i bet it is till going through all the files in the background since im running an ssd and never see that kind of delays with intellij.. so why would the "file watching" reach out of the specified folder? or are there some configurations that i am missing?

**Comment by syllant** [comment]
Probably same as #18

**Comment by syllant** [comment]
Please reopen if you still have the issue with version 1.11
