### ISSUE TITLE
OS-X Support?

### ISSUE THREAD

**Issue by stonefury** [syllant/idea-plugin-remotesynchronizer#17]
I'm new to intellij. I'm running 14 and 1.8 JDK.  Installed the plugin. I don't see a menu item in the Tools menu.

I also can't find Project Settings Panel. :).  I'm googling I'm googling.

**Comment by syllant** [comment]
Hi,

I guess you search the settings and not the actions? Settings are available in "Project settings" that have been renamed into "Preferences" in last versions of the IDE. They are located under "Other settings" section, but you can also look for "RemoteSynchronizer" in the search box.

I should probably update the doc :)

Sylvain
