### ISSUE TITLE
Synchronization is not triggered when updating java files

### ISSUE THREAD

**Issue by kalosh007** [syllant/idea-plugin-remotesynchronizer#19]
When I update java files the synchronization is not triggered. IDE is compiling java to class, but they are not copied.
My config below.
![1](https://cloud.githubusercontent.com/assets/12713655/7935610/8617a234-0932-11e5-8e8c-a11ae76648cb.png)
![2](https://cloud.githubusercontent.com/assets/12713655/7935611/86389e62-0932-11e5-90d2-d38fa01f4dad.png)

**Comment by syllant** [comment]
Hi,

You have not checked "Synchronize on save" but "Save before synchronize" instead. This means that you still have to launch explicitly synchronization, and files will be saved automatically.

If you check "Synchronize on save", files will be automatically synchronized when you'll save them.

Is it more clear?

Sylvain

**Comment by kalosh007** [comment]
Hello.
If I have checked sync on save, then my ide hangs. If I , on java file, choose sync current file, then I see in the logs that my java file is skipped, which is ok, because i don't want to have java copied, then class file is not synced.
Sorry for mistakes,i am writing from mobile.

**Comment by syllant** [comment]
I would recommend to send me the IDEA log (see Help menu), and to also attach a CPU usage profiling (see Tools menu).

Thanks

**Comment by kalosh007** [comment]
THis is basically a feature, not a bug. If I update the java file, synchronization is triggered for java file, not for class file. If I mark synch on save, then all the files mapped in the config are copied, regardless which file was updated.
