### ISSUE TITLE
unchanged files are synchronized, is this expected ?

### ISSUE THREAD

**Issue by jorgheymans** [syllant/idea-plugin-remotesynchronizer#2]
Hi,

I have setup remotesync on a maven project with 3 modules to sync to a local weblogic autodeploy directory. Every time i do ctrl-alt-* i can see from the log that every single class file in the project is first removed then readded. 

From the docs as i understand it should only copy those files for which the timestamp was updated.  Is this correct ?

Thanks
Jorg

**Comment by syllant** [comment]
Will reopen if any new feedback is provided.
