### ISSUE TITLE
RemoteSynchronizer not showing up in IntelliJ 16 EAP Settings Dialogue

### ISSUE THREAD

**Issue by maknesium** [syllant/idea-plugin-remotesynchronizer#20]
Hi,

I am using the upcoming version of IntelliJ Idea V16 EAP and I noticed that the remote synchronizer plugin is not showing up in the settings dialogue anymore.

As a workaround I now a) either edtit the projects \.idea\workspace.xml file directly (which holds the sync sources and targets) or start up my "old" IntelliJ 14, open the current project and update the path settings for RemoteSynchronizer.

I think this might only be a small issue. Did IntelliJ 16 change the way plugins are registered within the settings dialogue?

**Comment by maknesium** [comment]
This trick seems to fix it for IntelliJ IDEA 15 users: http://stackoverflow.com/questions/34177075/intellij-idea-15-ultimate-other-settings-missing-from-settings-window

Just to let you know.

**Comment by yaoxinghuo** [comment]
IDEA 2016.1 not show up setting dialog, I change this, and it works:
plugin.xml
line 41:

<extensions defaultExtensionNs="com.intellij">
    <projectService
      serviceInterface="org.sylfra.idea.plugins.remotesynchronizer.utils.ConfigStateComponent"
      serviceImplementation="org.sylfra.idea.plugins.remotesynchronizer.utils.ConfigStateComponent"/>
	  <projectConfigurable id="RemoteSynchronizer" displayName="Remote Synchronizer" instance="org.sylfra.idea.plugins.remotesynchronizer.RemoteSynchronizerPlugin"/>
  </extensions>

**Comment by maknesium** [comment]
GREAT! Thank you very much! I fixed it on my fork of the project and will send it a pull request :)

**Comment by syllant** [comment]
Thanks for the bug report and the fix.

**Comment by maknesium** [comment]
A pleasure! Since I use remoteSynchronizer daily, I was kind of tiered updating the workspace.xml with the sync sources/targets by hand ;)

Would be cool if you could push the new version to the jetbrains plugin repository for everyone to get the update (and be able to use remoteSynchronizer in IntelliJ 2015/2016).

**Comment by syllant** [comment]
Version 1.10 has been pushed some minutes ago.

**Comment by maknesium** [comment]
Great! Thanks!
