### ISSUE TITLE
Include installation instructions

### ISSUE THREAD

**Issue by fireproofsocks** [syllant/idea-plugin-remotesynchronizer#22]
Unfortunately, "Just use IDEA plugin manager." is not sufficient.  The help function in PHPStorm is quite limited, and there appear to be multiple types of plugins available, none of which seem to match up with what is in this repository.

**Comment by syllant** [comment]
Sorry, I don't understand your point. All IntelliJ-based products share the same Plugin Manager, and the way you install the RemoteSynchronizer plugin is the same for all these products. And this is also the same as any other plugin (cf. https://www.jetbrains.com/help/phpstorm/2016.1/installing-updating-and-uninstalling-repository-plugins.html). And there is only one "RemoteSynchronizer" in the repository :)

Can you explain what is not clear or not working for you?

Thanks

**Comment by fireproofsocks** [comment]
Sigh... if you don't understand the point, then I probably can't make you see it, but it does you absolutely no good to withhold information on installing your plugin: why spend all this time developing it and not offer a  couple sentences to actually make it useful?   I can't get this to work.  Other developers in our office can't make this work.  Thus the statement/issue: **the included instructions are insufficient.**  At a minimum, include the link above in your README.  Better still would be to actually walk through installing it with screenshots or button names.  It would be helpful to at least distinguish whether a user needs to click on "Install JetBrains Plugin" or "Browse Repositories..." or "Install Plugin from disk...".  It would be absolute minimal effort to include this information, but it could have a huge impact on the usability of the plugin.  I hope that point is something you can understand.

**Comment by syllant** [comment]
There is no point for me to explain this part. Someone finding hard to install a plugin on IntelliJ will probably struggle even more when using the plugin.

**Comment by fireproofsocks** [comment]
Here's a PR: https://github.com/syllant/idea-plugin-remotesynchronizer/pull/23  I hope it's not asking too much for you to add a single sentence of clarification to your README.

**Comment by syllant** [comment]
You would have spared your time by reading my last comment.

Also your PR is as useless as your condescending allusions in your comments: you point to the PhpStorm doc which represents probably less than 5% of the users among IntelliJ products, and you let "IDEA" which should be "IntelliJ".
