### ISSUE TITLE
"Synchronize on save" syncs all files, not only the saved one(s)

### ISSUE THREAD

**Issue by andreaswig** [syllant/idea-plugin-remotesynchronizer#25]
My project contains more than 7.000 files. When changing and saving just one, the plugin synchronizes all files instead of only the one that was just saved. This causes the IDE to hang for quite a while. Would it be possible to change the behaviour to only sync the file(s) that was/were just saved? There is still the option to manually start a sync on a folder.

**Comment by syllant** [comment]
Fair point. This should be investigated.

**Comment by syllant** [comment]
See #18
