### ISSUE TITLE
Do you use `rsync`?

### ISSUE THREAD

**Issue by macmladen** [syllant/idea-plugin-remotesynchronizer#29]
I am looking for a `rsync` based solution to synchronize with server and I am puzzled why JetBrains didn't still done so although requests date form 2011.

I found your plugin but I cannot find how it actually works although it looks like it uses `rsync`?

Can you clarify that? You could also add such information to description as that would greatly help for easier locating your plugin.

**Comment by syllant** [comment]
Hi,

No, it does not rely on rsync, it's a pure Java implementation with a much more humble scope. 

Everything useful for the usage should be in the README; for the implementation, nothing else than the codebase which is straightforward to review (well, much more than the rsync doc)
