### ISSUE TITLE
class file not found

### ISSUE THREAD

**Issue by smile962464** [syllant/idea-plugin-remotesynchronizer#31]
hi syllant
  Thank you for providing such a good plugin, it helped me to accomplish a lot of things, but I found a problem.look like this:
![image](https://cloud.githubusercontent.com/assets/5226695/22060607/705a2fde-ddac-11e6-9024-d60f307bd5ff.png)

I am using the version 1.10 of RemoteSynchronizer and Intellij IDEA 2016.1.4

Please look the screenshot of the configuration below.
![image](https://cloud.githubusercontent.com/assets/5226695/22060669/ac3462ea-ddac-11e6-845a-9b6ecb71122f.png)

Strangely enough, I had no problem debugging mode(download source code and compiling it myself).

My English is poor, please forgive me.

thinks
Martin

**Comment by smile962464** [comment]
i think you need project configuration：
![image](https://cloud.githubusercontent.com/assets/5226695/22061012/180ffac8-ddae-11e6-8325-3c7830e31fbd.png)

module configuration:
![image](https://cloud.githubusercontent.com/assets/5226695/22061076/5e52125a-ddae-11e6-8e88-2afec33b7ac6.png)

**Comment by syllant** [comment]
Hi Martin,

Seems like I can reproduce, there might be some changes in the latest IntelliJ APIs when the plugin needs to identify the class file of the selected source, I will have a look soon.

Thanks for reporting.

Sylvain

**Comment by smile962464** [comment]
haha, I also think it is the problem of IDEA APIs,because I use IDEA 13 no problem.

**Comment by syllant** [comment]
Issue related to the packaging, fixed.

Thanks again for reporting.

Sylvain
